-- Database-assigned total order for the dispatch queue.
--
-- WHY: newest-first ordering on agent_dispatch_messages was
-- `ORDER BY created_at DESC, id DESC`. `created_at` has millisecond
-- resolution while consecutive inserts complete well inside one millisecond
-- (measured: ~100% of back-to-back inserts share a timestamp), and `id` is a
-- random UUID that carries no insertion order -- so ties were broken at random
-- and newest-first held only ~50% of the time.
--
-- That is a correctness bug, not a test flake: collectVerdicts
-- (packages/overseer/src/pr-review-wiring.ts) requires receipts newest-first
-- because the first receipt seen for a message wins, so a coin-flipped tie can
-- let an older failed attempt outrank the later authoritative verdict.
--
-- A process-local monotonic clock cannot fix this: concurrent writers (server
-- plus worker, or two server instances) still collide, and a restarted writer
-- can emit timestamps older than rows already committed by its predecessor.
-- The order has to be assigned by the DATABASE, which is the only serialization
-- point every writer shares.
--
-- `seq` is that key. GENERATED BY DEFAULT (not ALWAYS) so the backfill and any
-- explicit-value restore/import can still write it.

BEGIN;

ALTER TABLE agent_dispatch_messages
  ADD COLUMN IF NOT EXISTS seq BIGINT;

-- Backfill existing rows in their best-known historical order. `created_at`
-- first (correct to the millisecond), then `id` as the stable tiebreak -- the
-- same arbitrary-but-deterministic order those rows already resolved to, so no
-- existing relative ordering is inverted by this migration.
WITH ordered AS (
  SELECT id, ROW_NUMBER() OVER (ORDER BY created_at ASC, id ASC) AS rn
    FROM agent_dispatch_messages
   WHERE seq IS NULL
)
UPDATE agent_dispatch_messages AS m
   SET seq = ordered.rn
  FROM ordered
 WHERE m.id = ordered.id;

-- NOT NULL must land BEFORE the identity is attached: Postgres rejects
-- ALTER COLUMN ... ADD GENERATED on a nullable column
-- ("must be declared NOT NULL before identity can be added").
ALTER TABLE agent_dispatch_messages
  ALTER COLUMN seq SET NOT NULL;

-- Attach the identity sequence only after the backfill, then advance it past
-- every value the backfill wrote so the first new insert cannot collide with a
-- historical row.
DO $$
DECLARE
  next_seq BIGINT;
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
     WHERE table_name = 'agent_dispatch_messages'
       AND column_name = 'seq'
       AND is_identity = 'YES'
  ) THEN
    ALTER TABLE agent_dispatch_messages
      ALTER COLUMN seq ADD GENERATED BY DEFAULT AS IDENTITY;
  END IF;

  SELECT COALESCE(MAX(seq), 0) + 1 INTO next_seq FROM agent_dispatch_messages;
  EXECUTE format(
    'ALTER TABLE agent_dispatch_messages ALTER COLUMN seq RESTART WITH %s',
    next_seq
  );
END $$;

-- Serves the newest-first reads: listMessages(subject_key) and
-- listMessagesByCorrelationPrefixWithoutSubjectKey both ORDER BY seq DESC
-- scoped to a recipient. seq leads because it IS the ordering key -- ordering
-- by created_at first would let a clock-skewed or restarted writer sort a later
-- row behind earlier ones.
CREATE INDEX IF NOT EXISTS idx_agent_dispatch_messages_recipient_seq
  ON agent_dispatch_messages (recipient, seq DESC);

COMMIT;
