/**
 * Tests for the check-completion recheck WIRING seams (bdc-harness #782,
 * Overseer App review finding at head 939d42f7 on 2026-09-07).
 *
 * THE BUG THESE PIN: `extractReviewSummary` is the only thing that can tell a
 * check-caused CHANGES_REQUESTED from a code-caused one, and it reads the
 * review work item's `result_body`. That body is `JSON.stringify(outcome)` for
 * a `SubmitOutcome` -- and the reviewer's posted finding text was not on that
 * type at all. A clean `changes_requested` sets no `reason` either, so the
 * function returned null, `verdictAuthorizesRecheck` refused the verdict, and
 * BOTH the webhook path and the stale sweep enqueued nothing. The re-review
 * this WO exists to deliver never happened.
 *
 * EVERY EXPECTED BODY HERE COMES FROM THE REAL SERIALIZER. The variants are
 * produced by running `runAndSubmitReview` against fake deps and stringifying
 * the outcome it actually returns -- never a hand-written literal, which would
 * pass while the persisted shape drifted underneath it.
 */
import { describe, expect, test } from 'bun:test';
import {
  runAndSubmitReview,
  type ReviewerVerdict,
  type ReviewWorkItem,
  type SubmitDeps,
  type SubmitOutcome,
} from '../pr-review-submit.ts';
import { extractReviewSummary, foldSubmitReceipts } from '../pr-review-check-wiring.ts';
import {
  ingestCheckCompletionEvent,
  verdictAuthorizesRecheck,
  type RecheckIngestDeps,
  type StandingVerdict,
} from '../pr-review-check-ingest.ts';
import { createHmac } from 'node:crypto';

const REVIEWER = 'thinman-overseer[bot]';
const HEAD = '5ac93b765ac93b765ac93b765ac93b765ac93b76';
const OWNER = 'thinmansoftware';
const REPO = 'bdc-harness';
const PR_NUMBER = 777;
const SECRET = 'test-webhook-secret';

const WORK: ReviewWorkItem = {
  correlationId: `pr-review:${OWNER}/${REPO}#${PR_NUMBER}@${HEAD}`,
  messageId: 'msg-1',
  owner: OWNER,
  repo: REPO,
  prNumber: PR_NUMBER,
  headSha: HEAD,
  author: 'bluedevilcollectibles',
};

/**
 * The exact finding line the reviewer emits for a red required check. Live
 * example, #777 @5ac93b76 on 2026-09-07 -- the run that had to be nudged by
 * hand, which is what #782 exists to automate.
 */
const CHECK_FINDING = '[major] checks/test (windows-latest): required check failed at this head';
/** A CODE finding: must never be auto-cleared by re-running a job. */
const CODE_FINDING =
  '[major] packages/overseer/src/pr-review-submit.ts: missing null guard on head';

/**
 * Run the REAL submit path against fake deps and return what the review worker
 * would persist: `JSON.stringify(outcome)`. This is the whole point -- the
 * fixtures below are generated by the same code that writes production rows.
 */
async function persistedResultBody(
  verdict: ReviewerVerdict,
  overrides: Partial<SubmitDeps> = {}
): Promise<{ body: string; outcome: SubmitOutcome }> {
  const deps: SubmitDeps = {
    reviewerIdentity: REVIEWER,
    runReviewer: async () => verdict,
    submitReview: async () => ({ submitted: true }),
    currentHeadSha: async () => HEAD,
    recordReceipt: async () => {},
    ...overrides,
  };
  const outcome = await runAndSubmitReview(WORK, deps);
  // Byte-for-byte what `review-worker-clock.ts` passes as `result_body`.
  return { body: JSON.stringify(outcome), outcome };
}

describe('extractReviewSummary reads the REAL persisted SubmitOutcome shape', () => {
  test('changes_requested with a CHECK finding recovers the summary (the #782 bug)', async () => {
    const { body, outcome } = await persistedResultBody({
      approved: false,
      summary: CHECK_FINDING,
      reviewedHeadSha: HEAD,
    });
    expect(outcome.disposition).toBe('changes_requested');
    // The regression guard: this branch carries NO `reason`, which is exactly
    // why reading `reason` alone recovered nothing.
    expect(outcome.reason).toBeUndefined();
    expect(extractReviewSummary(body)).toBe(CHECK_FINDING);
  });

  test('changes_requested with a CODE finding recovers that summary too', async () => {
    const { body } = await persistedResultBody({
      approved: false,
      summary: CODE_FINDING,
      reviewedHeadSha: HEAD,
    });
    // Recovering it is what lets the caller REFUSE it; a null here would fail
    // closed for the right answer by accident.
    expect(extractReviewSummary(body)).toBe(CODE_FINDING);
  });

  test('approved carries its summary', async () => {
    const { body, outcome } = await persistedResultBody({
      approved: true,
      summary: 'No blocking findings.',
      reviewedHeadSha: HEAD,
    });
    expect(outcome.disposition).toBe('approved');
    expect(extractReviewSummary(body)).toBe('No blocking findings.');
  });

  test('INDETERMINATE (a non-approving verdict with an explanatory summary) carries it', async () => {
    const indeterminate = 'Review indeterminate: the model returned no parseable verdict.';
    const { body, outcome } = await persistedResultBody({
      approved: false,
      summary: indeterminate,
      reviewedHeadSha: HEAD,
    });
    expect(outcome.disposition).toBe('changes_requested');
    expect(extractReviewSummary(body)).toBe(indeterminate);
  });

  test('CHECKS_PENDING release carries no summary and falls through to null', async () => {
    const { body, outcome } = await persistedResultBody({
      approved: false,
      summary: '',
      reviewedHeadSha: HEAD,
      checksPending: true,
    });
    expect(outcome.disposition).toBe('checks_pending');
    // Deliberate: nothing was evaluated. `checks_pending` authorizes a recheck
    // on its DISPOSITION alone, so it needs no summary -- and must not invent
    // one from its `reason`, which names the deferral, not a finding.
    expect(extractReviewSummary(body)).toBe('checks_not_terminal');
  });

  test('blocked_required_contexts_unavailable carries its explanatory summary', async () => {
    const blockedSummary = 'Required status-check contexts could not be read after 3 attempts.';
    const { body, outcome } = await persistedResultBody({
      approved: false,
      summary: blockedSummary,
      reviewedHeadSha: HEAD,
      requiredContextsUnavailable: true,
    });
    expect(outcome.disposition).toBe('blocked_required_contexts_unavailable');
    expect(extractReviewSummary(body)).toBe(blockedSummary);
  });

  test('rate_limited and transport_error deferrals recover no finding text', async () => {
    const rate = await persistedResultBody({
      approved: false,
      summary: '',
      reviewedHeadSha: HEAD,
      rateLimited: true,
    });
    expect(rate.outcome.disposition).toBe('rate_limited');
    expect(extractReviewSummary(rate.body)).toBe('github_rate_limited');

    const transport = await persistedResultBody({
      approved: false,
      summary: '',
      reviewedHeadSha: HEAD,
      transportError: true,
    });
    expect(transport.outcome.disposition).toBe('transport_error');
    expect(extractReviewSummary(transport.body)).toBe('review_transport_error');
  });

  test('absent, unparseable, and empty-summary bodies return null rather than throwing', () => {
    expect(extractReviewSummary(null)).toBeNull();
    expect(extractReviewSummary('')).toBeNull();
    expect(extractReviewSummary('not json at all')).toBeNull();
    expect(extractReviewSummary(JSON.stringify({ disposition: 'changes_requested' }))).toBeNull();
    expect(extractReviewSummary(JSON.stringify({ summary: '   ' }))).toBeNull();
  });

  test('a legacy body with only a reason still resolves (compatibility fallback)', () => {
    // Rows written before SubmitOutcome carried a summary.
    const legacy = JSON.stringify({ disposition: 'changes_requested', reason: CHECK_FINDING });
    expect(extractReviewSummary(legacy)).toBe(CHECK_FINDING);
  });
});

describe('the recovered summary drives the authorization decision', () => {
  test('a check-caused changes_requested authorizes; a code-caused one does not', async () => {
    const checkCaused = await persistedResultBody({
      approved: false,
      summary: CHECK_FINDING,
      reviewedHeadSha: HEAD,
    });
    const codeCaused = await persistedResultBody({
      approved: false,
      summary: CODE_FINDING,
      reviewedHeadSha: HEAD,
    });
    const asVerdict = (body: string): StandingVerdict => ({
      headSha: HEAD,
      disposition: 'changes_requested',
      summary: extractReviewSummary(body),
    });
    expect(verdictAuthorizesRecheck(asVerdict(checkCaused.body))).toBe(true);
    expect(verdictAuthorizesRecheck(asVerdict(codeCaused.body))).toBe(false);
  });

  test('a MIXED check-and-code changes_requested does not authorize', async () => {
    const mixed = await persistedResultBody({
      approved: false,
      summary: `${CHECK_FINDING}\n${CODE_FINDING}`,
      reviewedHeadSha: HEAD,
    });
    expect(
      verdictAuthorizesRecheck({
        headSha: HEAD,
        disposition: 'changes_requested',
        summary: extractReviewSummary(mixed.body),
      })
    ).toBe(false);
  });
});

describe('foldSubmitReceipts establishes WHICH verdict stands at a head', () => {
  const receipt = (disposition: string, headSha: string, created_at: string) => ({
    body: JSON.stringify({ kind: 'pr_review_submit_receipt', disposition, headSha }),
    created_at,
  });

  test('newest-first: the first terminal receipt for the head wins', () => {
    const verdict = foldSubmitReceipts(
      [
        receipt('changes_requested', HEAD, '2026-09-07T09:38:00Z'),
        receipt('checks_pending', HEAD, '2026-09-07T09:10:00Z'),
      ],
      HEAD
    );
    expect(verdict?.disposition).toBe('changes_requested');
    expect(verdict?.recordedAt).toBe('2026-09-07T09:38:00Z');
    // The receipt never carries the finding text; that is readStandingVerdict's
    // second read. Pinned so a future change cannot quietly start trusting it.
    expect(verdict?.summary).toBeNull();
  });

  test('receipts bound to a different head are skipped', () => {
    const otherHead = 'b'.repeat(40);
    expect(
      foldSubmitReceipts([receipt('changes_requested', otherHead, '2026-09-07T09:38:00Z')], HEAD)
    ).toBeNull();
  });

  test('malformed and foreign-kind rows are not verdict evidence', () => {
    expect(
      foldSubmitReceipts(
        [
          { body: '{ broken', created_at: '2026-09-07T09:40:00Z' },
          { body: JSON.stringify({ kind: 'other_receipt' }), created_at: '2026-09-07T09:39:00Z' },
        ],
        HEAD
      )
    ).toBeNull();
  });
});

/**
 * INTEGRATION: the whole recheck path, from a stored outcome to a queued row.
 *
 * This is the test the review finding asked for. It does not stub
 * `readStandingVerdict` with a convenient literal -- it reconstructs the
 * verdict from a result body the REAL submit path produced, then drives a real
 * `check_run` completed webhook through `ingestCheckCompletionEvent` and counts
 * the rows that come out the far end.
 */
describe('integration: stored outcome -> check_run completed -> exactly one re-review', () => {
  function sign(body: string): string {
    return `sha256=${createHmac('sha256', SECRET).update(body).digest('hex')}`;
  }

  function checkRunPayload(): string {
    return JSON.stringify({
      action: 'completed',
      check_run: {
        id: 999042,
        name: 'test (windows-latest)',
        status: 'completed',
        conclusion: 'success',
        head_sha: HEAD,
        pull_requests: [{ number: PR_NUMBER, head: { sha: HEAD } }],
      },
      repository: { name: REPO, owner: { login: OWNER } },
    });
  }

  function workflowRunPayload(name: string): string {
    return JSON.stringify({
      action: 'completed',
      workflow_run: {
        id: 4242,
        name,
        status: 'completed',
        conclusion: 'success',
        head_sha: HEAD,
        pull_requests: [{ number: PR_NUMBER, head: { sha: HEAD } }],
      },
      repository: { name: REPO, owner: { login: OWNER } },
    });
  }

  interface Enqueued {
    idempotencyKey: string;
    headSha: string;
    prNumber: number;
  }

  /**
   * Deps whose standing verdict is REBUILT from a persisted result body, the
   * same two reads `createRealRecheckIngestDeps.readStandingVerdict` performs:
   * the receipt for the disposition, the work item's result body for the text.
   */
  function makeDeps(
    resultBody: string,
    enqueued: Enqueued[],
    overrides: Partial<RecheckIngestDeps> = {}
  ): RecheckIngestDeps {
    const rows = new Map<string, string>();
    return {
      webhookSecret: SECRET,
      async readStandingVerdict(input) {
        const verdict = foldSubmitReceipts(
          [
            {
              body: JSON.stringify({
                kind: 'pr_review_submit_receipt',
                disposition: 'changes_requested',
                headSha: input.headSha,
              }),
              created_at: '2026-09-07T09:38:00Z',
            },
          ],
          input.headSha
        );
        if (!verdict) return null;
        return { ...verdict, summary: extractReviewSummary(resultBody) };
      },
      async enqueueRecheckWork(input) {
        enqueued.push({
          idempotencyKey: input.idempotencyKey,
          headSha: input.headSha,
          prNumber: input.prNumber,
        });
        const existing = rows.get(input.idempotencyKey);
        if (existing) return { messageId: existing, alreadyExisted: true };
        const messageId = `msg-${rows.size + 1}`;
        rows.set(input.idempotencyKey, messageId);
        return { messageId, alreadyExisted: false };
      },
      async recordReceipt() {},
      ...overrides,
    };
  }

  test('a check-caused CHANGES_REQUESTED queues exactly one re-review at the SAME head', async () => {
    const { body } = await persistedResultBody({
      approved: false,
      summary: CHECK_FINDING,
      reviewedHeadSha: HEAD,
    });
    const enqueued: Enqueued[] = [];
    const raw = checkRunPayload();
    const result = await ingestCheckCompletionEvent(
      {
        rawBody: raw,
        signature: sign(raw),
        eventType: 'check_run',
        deliveryId: 'delivery-1',
      },
      makeDeps(body, enqueued)
    );

    expect(result.disposition).toBe('queued');
    expect(result.status).toBe(200);
    expect(result.headSha).toBe(HEAD);
    expect(enqueued).toHaveLength(1);
    // SAME head -- a re-review, not a review of something new.
    expect(enqueued[0]?.headSha).toBe(HEAD);
    expect(enqueued[0]?.prNumber).toBe(PR_NUMBER);
  });

  test('a second identical delivery adds no second row', async () => {
    const { body } = await persistedResultBody({
      approved: false,
      summary: CHECK_FINDING,
      reviewedHeadSha: HEAD,
    });
    const enqueued: Enqueued[] = [];
    const deps = makeDeps(body, enqueued);
    const raw = checkRunPayload();
    await ingestCheckCompletionEvent(
      { rawBody: raw, signature: sign(raw), eventType: 'check_run', deliveryId: 'delivery-1' },
      deps
    );
    const second = await ingestCheckCompletionEvent(
      { rawBody: raw, signature: sign(raw), eventType: 'check_run', deliveryId: 'delivery-2' },
      deps
    );
    expect(second.disposition).toBe('duplicate_delivery');
    // The bound: ONE re-review per (head, completed check).
    expect(new Set(enqueued.map(row => row.idempotencyKey)).size).toBe(1);
  });

  test('NEGATIVE: a CODE-caused CHANGES_REQUESTED queues nothing', async () => {
    const { body } = await persistedResultBody({
      approved: false,
      summary: CODE_FINDING,
      reviewedHeadSha: HEAD,
    });
    const enqueued: Enqueued[] = [];
    const raw = checkRunPayload();
    const result = await ingestCheckCompletionEvent(
      {
        rawBody: raw,
        signature: sign(raw),
        eventType: 'check_run',
        deliveryId: 'delivery-3',
      },
      makeDeps(body, enqueued)
    );

    expect(result.disposition).toBe('ignored_no_authorizing_verdict');
    // The code did not change, so the finding still stands.
    expect(enqueued).toHaveLength(0);
  });

  test('NEGATIVE: a MIXED check-and-code CHANGES_REQUESTED queues nothing', async () => {
    const { body } = await persistedResultBody({
      approved: false,
      summary: `${CHECK_FINDING}\n${CODE_FINDING}`,
      reviewedHeadSha: HEAD,
    });
    const enqueued: Enqueued[] = [];
    const raw = checkRunPayload();
    const result = await ingestCheckCompletionEvent(
      {
        rawBody: raw,
        signature: sign(raw),
        eventType: 'check_run',
        deliveryId: 'delivery-mixed',
      },
      makeDeps(body, enqueued)
    );

    expect(result.disposition).toBe('ignored_no_authorizing_verdict');
    expect(enqueued).toHaveLength(0);
  });

  test('NEGATIVE: a passing Gitleaks workflow_run queues nothing for a named windows test', async () => {
    const { body } = await persistedResultBody({
      approved: false,
      summary: CHECK_FINDING,
      reviewedHeadSha: HEAD,
    });
    const enqueued: Enqueued[] = [];
    const raw = workflowRunPayload('Gitleaks');
    const result = await ingestCheckCompletionEvent(
      {
        rawBody: raw,
        signature: sign(raw),
        eventType: 'workflow_run',
        deliveryId: 'delivery-gitleaks',
      },
      makeDeps(body, enqueued)
    );
    expect(result.disposition).toBe('ignored_no_authorizing_verdict');
    expect(enqueued).toHaveLength(0);
  });

  test('a passing workflow_run whose name matches the named check queues exactly one re-review', async () => {
    const { body } = await persistedResultBody({
      approved: false,
      summary: CHECK_FINDING,
      reviewedHeadSha: HEAD,
    });
    const enqueued: Enqueued[] = [];
    const raw = workflowRunPayload('test');
    const result = await ingestCheckCompletionEvent(
      {
        rawBody: raw,
        signature: sign(raw),
        eventType: 'workflow_run',
        deliveryId: 'delivery-wf-match',
      },
      makeDeps(body, enqueued)
    );
    expect(result.disposition).toBe('queued');
    expect(enqueued).toHaveLength(1);
  });

  test('unmatched workflow_run enqueues when listForRef shows the named check green', async () => {
    const { body } = await persistedResultBody({
      approved: false,
      summary: CHECK_FINDING,
      reviewedHeadSha: HEAD,
    });
    const enqueued: Enqueued[] = [];
    const raw = workflowRunPayload('Gitleaks');
    const result = await ingestCheckCompletionEvent(
      {
        rawBody: raw,
        signature: sign(raw),
        eventType: 'workflow_run',
        deliveryId: 'delivery-wf-list-green',
      },
      makeDeps(body, enqueued, {
        async listCheckRunsForRef() {
          return {
            complete: true,
            runs: [
              { id: 1, name: 'Gitleaks', status: 'completed', conclusion: 'success' },
              { id: 2, name: 'test (windows-latest)', status: 'completed', conclusion: 'success' },
            ],
          };
        },
      })
    );
    expect(result.disposition).toBe('queued');
    expect(enqueued).toHaveLength(1);
  });

  test('unmatched workflow_run queues nothing when listForRef shows the named check still red', async () => {
    const { body } = await persistedResultBody({
      approved: false,
      summary: CHECK_FINDING,
      reviewedHeadSha: HEAD,
    });
    const enqueued: Enqueued[] = [];
    const raw = workflowRunPayload('Gitleaks');
    const result = await ingestCheckCompletionEvent(
      {
        rawBody: raw,
        signature: sign(raw),
        eventType: 'workflow_run',
        deliveryId: 'delivery-wf-list-red',
      },
      makeDeps(body, enqueued, {
        async listCheckRunsForRef() {
          return {
            complete: true,
            runs: [
              { id: 1, name: 'Gitleaks', status: 'completed', conclusion: 'success' },
              { id: 2, name: 'test (windows-latest)', status: 'completed', conclusion: 'failure' },
            ],
          };
        },
      })
    );
    expect(result.disposition).toBe('ignored_no_authorizing_verdict');
    expect(enqueued).toHaveLength(0);
  });
});
