import { createHash, randomUUID } from 'crypto';
import type { TaskmasterAction, TaskmasterControl } from '@archon/core/db';
import { classifyThread, computeNextAction, type ThreadState, type Proposal } from './rules';
import { validateProposal } from './guard';
import { recordTickHeartbeat } from './deadman';

const getLog=()=>console; let timer:ReturnType<typeof setInterval>|undefined; let inFlight=false;
const confirmations=new Map<string,number>();
let githubBackoffUntil=0;
export interface LoopDeps { now:()=>Date; readThreads:()=>Promise<ThreadState[]>; getControl:()=>Promise<TaskmasterControl>; actions:(since:string,ref?:string)=>Promise<TaskmasterAction[]>; journal:(a:TaskmasterAction)=>Promise<TaskmasterAction>; markOutcome:(key:string,outcome:string)=>Promise<void>; send:(a:any)=>Promise<any>; heartbeat:(now:number)=>void }
async function core(){return import('@archon/core/db')}
export async function githubThreads():Promise<ThreadState[]>{if(Date.now()<githubBackoffUntil)throw new Error('taskmaster_github_backoff_active');const repo=process.env.TASKMASTER_GITHUB_REPO??'bluedevilcollectibles/bdc-harness';const headers:Record<string,string>={accept:'application/vnd.github+json','user-agent':'bdc-taskmaster'};if(process.env.GITHUB_TOKEN)headers.authorization=`Bearer ${process.env.GITHUB_TOKEN}`;const response=await fetch(`https://api.github.com/repos/${repo}/issues?state=open&labels=wo%2Carc&per_page=100`,{headers});const remaining=Number.parseInt(response.headers.get('x-ratelimit-remaining')??'',10);if(remaining<=1){const reset=Number.parseInt(response.headers.get('x-ratelimit-reset')??'',10);githubBackoffUntil=Number.isFinite(reset)?reset*1000:Date.now()+60000;}if(!response.ok){getLog().warn('taskmaster.github_read_failed',response.status);throw new Error(`taskmaster_github_read_failed:${response.status}`)}const issues=await response.json() as Array<{number:number;updated_at:string;labels:Array<{name?:string}>;assignee?:unknown;title:string}>;return issues.map(issue=>{const labels=issue.labels.map(l=>l.name?.toUpperCase()??'');const priority=(labels.find(l=>/^P[0-3]$/.test(l))??'P2') as ThreadState['priority'];return{ref:`github:${repo}#${issue.number}`,priority,lastActivityAt:issue.updated_at,unclaimed:priority==='P0'&&!issue.assignee,body:issue.title};});}
export async function defaultThreads(readQueued=async()=>(await core()).listMessages({status:'queued',limit:100}),readGithub=githubThreads):Promise<ThreadState[]>{const queued=await readQueued();const rulings:ThreadState[]=queued.filter(m=>m.task_type==='board_motion'&&m.addressed_at===null).map(m=>({ref:m.motion_id??m.id,priority:m.priority==='blocker'?'P0':'P1',lastActivityAt:m.created_at,kind:'ruling',recipient:m.resolved_recipient??m.recipient,body:m.body}));let github:ThreadState[]=[];try{github=await readGithub()}catch(error){getLog().warn('taskmaster.github_discovery_unavailable',error)}const day=new Date().toISOString().slice(0,10);return[...rulings,...github,{ref:`digest:${day}`,priority:'P3',lastActivityAt:new Date().toISOString(),kind:'digest'}];}
const defaults:LoopDeps={now:()=>new Date(),readThreads:defaultThreads,getControl:async()=>(await core()).getPauseState(),actions:async(s,r)=>(await core()).getActionsSince(s,r),journal:async a=>(await core()).recordAction(a),markOutcome:async(k,o)=>(await core()).updateActionOutcome(k,o),send:async a=>(await core()).createMessage(a),heartbeat:recordTickHeartbeat};
function baseKey(p:Proposal,epoch:number){return `taskmaster:${epoch}:${p.actionType}:${p.threadRef}`;}
function retryMs(thread:ThreadState){return thread.priority==='P0'?30*60e3:thread.priority==='P1'?4*60*60e3:24*60*60e3;}
export async function tick(overrides:Partial<LoopDeps>={}):Promise<{effects:number;deferred:number}>{const d={...defaults,...overrides};const now=d.now();d.heartbeat(now.getTime());const control=await d.getControl();const threads=await d.readThreads();let effects=0,deferred=0;for(const thread of threads){const proposal=computeNextAction(thread,classifyThread(thread,now));if(!proposal)continue;const confirmationKey=baseKey(proposal,control.epoch);const recent=await d.actions(new Date(now.getTime()-24*60*60e3).toISOString(),thread.ref);const sent=recent.filter(a=>a.outcome==='sent');const lastSent=sent.at(-1);if(sent.length>=3||lastSent&&now.getTime()-new Date(lastSent.created_at??0).getTime()<retryMs(thread))continue;const count=(confirmations.get(confirmationKey)??0)+1;confirmations.set(confirmationKey,count);const urgent=proposal.actionType==='deliver_ruling'||proposal.actionType==='escalate_p0';if(!urgent&&count<2)continue;const key=`${confirmationKey}:${now.getTime()}:${recent.length}`;const guard=validateProposal(proposal);let outcome=!guard.allowed?'rejected':effects>=10?'deferred':control.pause_state!=='RUNNING'&&proposal.actionType!=='escalate_p0'?'parked':'in_flight';await d.journal({thread_ref:thread.ref,action_type:proposal.actionType,proposal_json:JSON.stringify(proposal),idempotency_key:key,before_hash:createHash('sha256').update(JSON.stringify(thread)).digest('hex'),proof_predicate:'dispatch row exists',proof_deadline_at:new Date(now.getTime()+48*60*60e3).toISOString(),outcome});if(outcome==='deferred'){deferred++;continue}if(outcome!=='in_flight')continue;const fresh=await d.getControl();if(fresh.epoch!==control.epoch||(fresh.pause_state!=='RUNNING'&&proposal.actionType!=='escalate_p0'))continue;try{await d.send({correlation_id:thread.ref,idempotency_key:key,task_type:'agent_message',sender:'taskmaster',recipient:proposal.recipient,body:proposal.body,priority:proposal.priority});await d.markOutcome(key,'sent');effects++;}catch(error){await d.markOutcome(key,'failed');getLog().warn('taskmaster.dispatch_failed',error)}}return{effects,deferred};}
export function startTaskmaster():void{if(process.env.NODE_ENV==='test'||timer)return;const parsed=Number.parseInt(process.env.TASKMASTER_INTERVAL_MS??'',10);const interval=Number.isInteger(parsed)?parsed:60000;if(interval===0)return;const ownerId=`taskmaster:${randomUUID()}`;const run=async()=>{if(inFlight)return;inFlight=true;try{const result=await tick();if(result.effects||result.deferred)getLog().info('taskmaster.tick',result,ownerId);}catch(error){getLog().error('taskmaster.failed',error,ownerId);}finally{inFlight=false;}};timer=setInterval(()=>void run(),interval);timer.unref?.();void run();}
export function stopTaskmaster():void{if(timer)clearInterval(timer);timer=undefined;inFlight=false;}
